# Generated by Django 3.0.4 on 2020-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Student'), (1, 'Trainer'), (2, 'Student+ClubLeader'), (3, 'Admin')], default=0)),
                ('course_id', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
