# Generated by Django 3.0.4 on 2020-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
