# Generated by Django 3.0.4 on 2020-04-11 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20200405_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='choice_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='semester',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='semester',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
