# Generated by Django 3.0.5 on 2020-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20200414_1851'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='training',
            constraint=models.UniqueConstraint(fields=('group', 'start', 'end'), name='unique_training'),
        ),
    ]
