# Generated by Django 3.0.5 on 2020-04-17 11:38

from django.db import migrations, models
import django.db.models.deletion
import sport.models.semester


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20200417_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Schedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Training'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='choice_deadline',
            field=models.DateField(default=sport.models.semester.today),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end',
            field=models.DateField(default=sport.models.semester.today),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start',
            field=models.DateField(default=sport.models.semester.today),
        ),
    ]
