# Generated by Django 3.0.5 on 2020-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_auto_20200417_1438'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('training', 'student'), name='unique_attendance'),
        ),
    ]
