# Generated by Django 3.0.5 on 2020-05-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_auto_20200428_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'training class',
                'verbose_name_plural': 'training classes',
                'db_table': 'training_class',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.TrainingClass'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.TrainingClass'),
        ),
    ]
