# Generated by Django 3.0.6 on 2020-06-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_auto_20200529_0556'),
        ('sport', '0012_make_profiles'),
    ]

    operations = [
    ]
