# Generated by Django 3.0.7 on 2020-06-15 10:58

from django.db import migrations, models
import sport.models.reference


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0016_auto_20200610_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=models.ImageField(upload_to=sport.models.reference.get_reference_path),
        ),
    ]
