# Generated by Django 3.0.7 on 2020-06-15 10:58

from django.db import migrations, models
import sport.models.attendance


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0017_auto_20200615_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[sport.models.attendance.validate_hours]),
        ),
    ]
