# Generated by Django 3.0.7 on 2020-06-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0016_schedule_backref_weekday_fix'),
        ('sport', '0018_extend_attendance_hour_limit'),
    ]

    operations = [
    ]
