# Generated by Django 3.0.7 on 2020-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0020_add_medical_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='student',
            field=models.IntegerField(),
        ),
    ]
