# Generated by Django 3.0.7 on 2020-06-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0022_change_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_old',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='trainer',
            new_name='trainer_old',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='student',
            new_name='student_old',
        ),
    ]
