# Generated by Django 3.0.7 on 2020-06-29 12:49

from django.db import migrations, models
import django.db.models.deletion


def copy_fk(apps, schema_editor):
    Student = apps.get_model("sport", "Student")
    Trainer = apps.get_model("sport", "Trainer")

    student_id = Student.objects.filter(
        id=models.OuterRef("student_old")
    ).values_list("user_id")[:1]

    trainer_id = Trainer.objects.filter(
        id=models.OuterRef("trainer_old")
    ).values_list("user_id")[:1]

    Attendance = apps.get_model("sport", "Attendance")
    Attendance.objects.update(
        student=models.Subquery(student_id)
    )

    Enroll = apps.get_model("sport", "Enroll")
    Enroll.objects.update(
        student=models.Subquery(student_id)
    )

    Reference = apps.get_model("sport", "Reference")
    Reference.objects.update(
        student=models.Subquery(student_id)
    )

    Group = apps.get_model("sport", "Group")
    Group.objects.update(
        trainer=models.Subquery(trainer_id)
    )


class Migration(migrations.Migration):
    dependencies = [
        ('sport', '0024_finish_rename_old_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='sport.Trainer'),
        ),
        migrations.AddField(
            model_name='reference',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.RunPython(
            copy_fk,
            reverse_code=migrations.RunPython.noop
        ),
    ]
