# Generated by Django 3.0.7 on 2020-06-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0025_create_nullable_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_old',
        ),
        migrations.RemoveField(
            model_name='group',
            name='trainer_old',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='student_old',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student', 'group')},
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='student_old',
        ),
    ]
