# Generated by Django 3.0.7 on 2020-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0027_auto_20200629_1438'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('training', 'student'), name='unique_attendance'),
        ),
    ]
