# Generated by Django 3.0.7 on 2020-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sport', '0028_auto_20200629_1735'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX auth_user_search_index ON auth_user (lower(first_name || \' \' || last_name) text_pattern_ops, lower(last_name) text_pattern_ops, lower(email) text_pattern_ops);',
            reverse_sql='DROP INDEX auth_user_search_index;'
        ),
    ]
