# Generated by Django 3.0.7 on 2020-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0029_add_user_text_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='positive_hours',
        ),
        migrations.AddField(
            model_name='reference',
            name='approval',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(hours__gte=0), name='positive_hours'),
        ),
    ]
