# Generated by Django 3.0.7 on 2020-07-01 14:50

from django.db import migrations, models
import sport.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0029_add_user_text_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveSmallIntegerField(default=sport.utils.get_current_study_year),
        ),
    ]
