# Generated by Django 3.0.7 on 2020-07-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0030_auto_20200703_0840'),
        ('sport', '0030_student_enrollment_year'),
    ]

    operations = [
    ]
