# Generated by Django 3.0.7 on 2020-07-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0032_medicalgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='minimum_medical_group',
            field=models.ForeignKey(default=-2, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.MedicalGroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_group',
            field=models.ForeignKey(default=-2, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.MedicalGroup'),
        ),
    ]
