# Generated by Django 3.0.7 on 2020-08-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0035_medical_group_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalgroupreference',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
