# Generated by Django 3.0.7 on 2020-08-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0036_medical_group_reference_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalgroupreference',
            name='semester',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sport.Semester'),
            preserve_default=False,
        ),
    ]
