# Generated by Django 3.0.7 on 2020-08-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0038_auto_20200817_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
