# Generated by Django 3.0.7 on 2021-01-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0039_auto_20200830_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
