# Generated by Django 3.0.7 on 2020-12-31 07:45

from os import getenv

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sport', '0039_auto_20200830_1221'),
    ]

    grafana_user = getenv('GRAFANA_DB_USER')
    grafana_password = getenv('GRAFANA_DB_USER_PASSWORD')

    operations = {
        migrations.RunSQL(
            f"create role {grafana_user} with login "
            f"password '{grafana_password}' "
            "nosuperuser inherit nocreatedb nocreaterole noreplication "
            "valid until 'infinity';",
            reverse_sql=f"drop role {grafana_user};"
        ),
    }
