# Generated by Django 3.0.7 on 2020-12-31 07:45

from os import getenv

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sport', '0039_auto_20200830_1221'),
    ]
    # Needed to preserve Django state
    # https://docs.djangoproject.com/en/3.1/ref/migration-operations/#runsql
    atomic = False

    grafana_user = getenv('GRAFANA_DB_USER')
    grafana_password = getenv('GRAFANA_DB_USER_PASSWORD')

    operations = {
        migrations.RunSQL(
            # Create user for grafana if not exists already
            f'''
            DO
            $do$
            BEGIN
               IF NOT EXISTS (
                  SELECT FROM pg_catalog.pg_roles
                  WHERE  rolname = '{grafana_user}') THEN
                  create role {grafana_user} 
                    with login password '{grafana_password}' 
                    nosuperuser inherit nocreatedb nocreaterole noreplication 
                    valid until 'infinity';
               END IF;
            END
            $do$;
            ''',
            reverse_sql=f"drop role {grafana_user};"
        ),
    }
