# Generated by Django 3.0.7 on 2020-12-31 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sport', '0041_remove_is_primary_enroll_field'),
    ]

    operations = [
        migrations.RunSQL(
            """
create or replace function get_primary_groups_in_semester(query_semester_id int)
    returns table
            (
                student_id int,
                group_id   int
            )
as
$$
begin
    return query with ranked_attended_groups as (
        select a.student_id                     as student_id,
               g.id                             as group_id,
               count(a.id)                      as attendance_count,
               row_number() over (
                partition by a.student_id 
                order by count(a.id) desc 
                )                               as rk
        from "group" g
                 join training t on g.id = t.group_id
                 join attendance a on t.id = a.training_id
                 join sport s on g.sport_id = s.id
        where (
            s.special = FALSE                   -- IU groups
            or (s.special = TRUE and g.is_club = TRUE) -- Clubs
            ) and g.semester_id = query_semester_id -- In current semester
        group by a.student_id, g.id
    ),
         best_suit as (
             select rag.student_id, rag.group_id
             from ranked_attended_groups rag
             where rk = 1
         )
    select *
    from best_suit;
end
$$
    language plpgsql;
""",
            reverse_sql="drop function if exists "
                        "get_primary_groups_in_semester;")
    ]
