# Generated by Django 3.0.7 on 2021-01-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0041_grant_grafana_permissions'),
        ('sport', '0040_student_telegram'),
    ]

    operations = [
    ]
