# Generated by Django 3.0.7 on 2021-01-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0044_auto_20210114_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfSportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('application_rule', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'self_sport_group',
            },
        ),
        migrations.AddField(
            model_name='selfsportreport',
            name='training_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.SelfSportType'),
        ),
    ]
