# Generated by Django 3.0.7 on 2021-01-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0044_auto_20210114_1452'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='selfsportreport',
            name='link_xor_image',
        ),
        migrations.AddConstraint(
            model_name='selfsportreport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('link__isnull', True), models.Q(_negated=True, image__exact='')), models.Q(('image__exact', ''), ('link__isnull', False)), _connector='OR'), name='link_xor_image'),
        ),
    ]
