# Generated by Django 3.0.7 on 2021-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0044_auto_20210114_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
