# Generated by Django 3.0.7 on 2021-01-16 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0045_self_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsportreport',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
