# Generated by Django 3.0.7 on 2021-01-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0046_self_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsporttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
