# Generated by Django 3.0.7 on 2021-01-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0046_medicalgroupreference_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalgroupreference',
            name='resolved',
            field=models.BooleanField(null=True),
        ),
    ]
