# Generated by Django 3.0.7 on 2021-01-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0044_auto_20210114_1002'),
        ('sport', '0046_limit_selfsport_link_schemes'),
    ]

    operations = [
    ]
