# Generated by Django 3.0.7 on 2021-01-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0047_merge_20210116_1854'),
        ('sport', '0047_auto_20210115_1957'),
    ]

    operations = [
    ]
