# Generated by Django 3.0.7 on 2021-01-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0048_remove_limit_on_user_for_trainer'),
        ('sport', '0049_selfsportreport_comment'),
    ]

    operations = [
    ]
