# Generated by Django 3.0.7 on 2021-01-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0050_merge_20210122_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='cause_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='sport.Reference'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='cause_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='sport.SelfSportReport'),
        ),
    ]
