# Generated by Django 3.0.7 on 2021-02-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0052_migrate_self_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedicalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.MedicalGroup')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Student')),
            ],
            options={
                'verbose_name_plural': 'student medical groups',
                'db_table': 'student_medical_group',
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
