# Generated by Django 3.1.6 on 2021-06-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0052_migrate_self_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'student statuses',
                'db_table': 'student_status',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.studentstatus'),
        ),
    ]
