# Generated by Django 3.0.7 on 2021-01-26 20:34
from datetime import datetime, time

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def migrate(apps, schema_editor):
    Semester = apps.get_model("sport", "Semester")
    Student = apps.get_model("sport", "Student")
    StudentMedicalGroup = apps.get_model("sport", "StudentMedicalGroup")
    for semester in Semester.objects.all():
        for student in Student.objects.all():
            obj, _ = StudentMedicalGroup.objects.get_or_create(student=student, semester=semester, defaults={
                'medical_group_id': student.medical_group_id
            })
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0053_studentmedicalgroup'),
    ]

    operations = [
        migrations.RunPython(
            migrate,
            reverse_code=migrations.RunPython.noop
        ),
    ]
