# Generated by Django 3.1.8 on 2021-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0053_auto_20210610_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='trainers',
            field=models.ManyToManyField(blank=True, null=True, related_name='m2m', to='sport.Trainer'),
        ),
    ]
