# Generated by Django 3.1.8 on 2021-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0054_group_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='m2m', to='sport.Trainer'),
        ),
    ]
