# Generated by Django 3.1.8 on 2021-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0054_add_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
