# Generated by Django 3.1.8 on 2021-07-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0054_add_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, medical_group__name='Medical checkup not passed'), on_delete=django.db.models.deletion.CASCADE, to='sport.student'),
        ),
    ]
