# Generated by Django 3.1.8 on 2021-07-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0054_add_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('medical_group__name', 'General'), ('medical_group__name', 'Preparative'), ('medical_group__name', 'Special 1'), ('medical_group__name', 'Special 2'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='sport.student'),
        ),
    ]
