# Generated by Django 3.1.8 on 2021-07-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0055_student_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sport'),
        ),
    ]
