# Generated by Django 3.1.8 on 2021-07-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0056_group_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'medical_group__name': 'Special 2'}, on_delete=django.db.models.deletion.CASCADE, to='sport.student'),
        ),
    ]
