# Generated by Django 3.1.8 on 2021-07-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0056_student_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('go_to_another_group', 'Can go to another group in the same type of sport'),
                                     ("choose_group", "Can choose group")], 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='selfsporttype',
            options={
                'permissions': [('more_than_10_hours_of_self_sport', 'Can have more then 10 hours of self sport')]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('see_calendar', 'Can see calendar')], 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'permissions': [('choose_sport', 'Can choose type of sport'),
                                     ('go_to_another_sport', 'Can got to group of the another type of sport')],
                     'verbose_name': 'sport type', 'verbose_name_plural': 'sport types'},
        ),
    ]
