# Generated by Django 3.1.8 on 2021-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0057_add_semester_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'custom permissions',
                'db_table': 'custom_permission',
                'permissions': [('choose_sport', 'Can choose type of sport'), ('go_to_another_sport', 'Can go to group of the another type of sport'), ('see_calendar', 'Can see calendar'), ('go_to_another_group', 'Can go to another group in the same type of sport'), ('choose_group', 'Can choose group'), ('more_than_10_hours_of_self_sport', 'Can have more then 10 hours of self sport')],
            },
        ),
        migrations.RunSQL('''
        INSERT INTO custom_permission (id, name, description) VALUES 
        (0, 'choose_sport', 'Can choose type of sport'),
        (1, 'go_to_another_sport', 'Can go to group of the another type of sport'),
        (2, 'see_calendar', 'Can see calendar'),
        (3, 'go_to_another_group', 'Can go to another group in the same type of sport'),
        (4, 'choose_group', 'Can choose group'),
        (5, 'more_than_10_hours_of_self_sport', 'Can have more then 10 hours of self sport');
        ''', '')
    ]
