# Generated by Django 3.1.8 on 2021-07-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0058_custompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sport'),
        ),
    ]
