# Generated by Django 3.1.8 on 2021-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0058_custompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfsportreport',
            name='debt',
            field=models.BooleanField(default=False),
        ),
    ]
