# Generated by Django 3.1.8 on 2021-07-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0059_student_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.sport'),
        ),
    ]
