# Generated by Django 3.1.8 on 2021-08-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0064_add_academic_leave_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('medical_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.medicalgroup')),
                ('medical_group_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.medicalgroupreference')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.student')),
            ],
            options={
                'verbose_name_plural': 'medical groups history',
                'db_table': 'medical_group_history',
            },
        ),
    ]
