# Generated by Django 3.1.8 on 2021-08-02 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0066_change_medical_reference_in_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reference',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reference',
            name='student_comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
