# Generated by Django 3.1.8 on 2021-08-02 13:49

from django.db import migrations, models
import sport.models.reference


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0067_auto_20210802_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='end',
            field=models.DateField(default=sport.models.reference.today),
        ),
        migrations.AddField(
            model_name='reference',
            name='start',
            field=models.DateField(default=sport.models.reference.today),
        ),
        migrations.AddField(
            model_name='reference',
            name='student_comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='number_hours_one_day_ill',
            field=models.IntegerField(default=1),
        ),
    ]
