# Generated by Django 3.1.8 on 2021-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0068_auto_20210802_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='minimum_medical_group',
        ),
        migrations.AddField(
            model_name='group',
            name='allowed_medical_groups',
            field=models.ManyToManyField(blank=True, to='sport.MedicalGroup'),
        ),
    ]
