# Generated by Django 3.1.8 on 2021-08-02 10:36

from django.db import migrations, models
import sport.models.reference


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0068_add_ill_hours_to_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='end',
            field=models.DateField(default=sport.models.reference.today),
        ),
        migrations.AlterField(
            model_name='reference',
            name='start',
            field=models.DateField(default=sport.models.reference.today),
        ),
    ]
