# Generated by Django 3.1.8 on 2021-08-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0068_auto_20210802_1649'),
        ('sport', '0063_auto_20210802_0900'),
    ]

    operations = [
    ]
