# Generated by Django 3.1.8 on 2021-08-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0069_auto_20210805_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='sport.group'),
        ),
    ]
