# Generated by Django 3.1.8 on 2021-08-08 12:59

from django.db import migrations, models
import sport.models.attendance


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0071_add_parsed_data_student_comment_fields'),
    ]

    operations = [
        migrations.RunSQL('UPDATE attendance SET hours = CEIL(hours)'),
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.IntegerField(default=1, validators=[sport.models.attendance.validate_hours]),
        ),
    ]
