# Generated by Django 3.1.8 on 2021-08-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0074_reference_comment_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='minimum_medical_group',
        ),
        migrations.AddField(
            model_name='group',
            name='allowed_medical_groups',
            field=models.ManyToManyField(blank=True, to='sport.MedicalGroup'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls',
                                    to='sport.group'),
        ),
    ]
