# Generated by Django 3.1.8 on 2021-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0076_add_nullify_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='increase_course',
            field=models.BooleanField(default=False),
        ),
    ]
