# Generated by Django 3.1.8 on 2021-08-16 12:41

from django.db import migrations, models
import sport.models.student


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0078_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[sport.models.student.validate_course]),
        ),
    ]
