# Generated by Django 3.1.8 on 2021-12-05 09:57

from django.db import migrations
import smartfields.fields
import sport.models.reference


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0081_faqcategory_faqelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=smartfields.fields.ImageField(upload_to=sport.models.reference.get_reference_path),
        ),
    ]
