# Generated by Django 3.1.8 on 2021-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0083_fitnesstestexercise_fitnesstestgrading_fitnesstestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstestresult',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
