# Generated by Django 3.1.8 on 2021-12-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0089_auto_20211208_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessTestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='fitnesstestresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.fitnesstestsession'),
        ),
    ]
