# Generated by Django 3.1.8 on 2021-12-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0090_auto_20211208_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnesstestsession',
            old_name='start',
            new_name='date',
        ),
        migrations.AddField(
            model_name='fitnesstestsession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.trainer'),
        ),
    ]
