# Generated by Django 3.1.8 on 2022-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0097_auto_20220116_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allowed_qr',
            field=models.IntegerField(choices=[(-1, 'Does not matter'), (0, 'No'), (1, 'Yes')], default=-1),
        ),
    ]
