# Generated by Django 3.1.8 on 2021-09-13 22:41

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0099_auto_20220117_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqelement',
            name='answer',
            field=django_quill.fields.QuillField(),
        ),
    ]
