# Generated by Django 3.1.8 on 2022-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0099_auto_20220117_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Technical'),
        ),
    ]
