# Generated by Django 3.1.8 on 2022-02-28 22:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0100_auto_20220223_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqelement',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
