# Generated by Django 3.1.8 on 2022-05-03 10:20

from django.db import migrations, models
import django.db.models.deletion


def move_semester(apps, schema_editor):
    FitnessTestGrading = apps.get_model("sport", "FitnessTestGrading")
    FitnessTestExercise = apps.get_model("sport", "FitnessTestExercise")
    Semester = apps.get_model("sport", "Semester")
    semesters = FitnessTestGrading.objects.all().values('semester_id').distinct()
    for s in semesters:
        gradings = FitnessTestGrading.objects.filter(semester_id=s['semester_id'])
        for g in gradings:
            if g.exercise.semester is None:
                g.exercise.semester = Semester.objects.get(pk=s['semester_id'])
                g.exercise.save()
            else:
                ex = g.exercise
                if ex.semester.pk != s['semester_id']:
                    check = FitnessTestExercise.objects.filter(exercise_name=ex.exercise_name,
                                                               semester__pk=s['semester_id'])
                    if check.exists():
                        g.exercise = check[0]
                    else:
                        ex.pk = None
                        ex.semester = Semester.objects.get(pk=s['semester_id'])
                        ex.save()
                        g.exercise = ex
            g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0102_fitnesstestexercise_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstestexercise',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='sport.semester'),
        ),
        migrations.RunPython(move_semester, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='fitnesstestresult',
            name='student_semester_exercise',
        ),
    ]
