# Generated by Django 3.1.8 on 2022-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0102_fitnesstestexercise_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesstestgrading',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='fitnesstestresult',
            name='semester',
        ),
        migrations.RemoveConstraint(
            model_name='fitnesstestresult',
            name='student_semester_exercise',
        ),
        migrations.AddConstraint(
            model_name='fitnesstestresult',
            constraint=models.UniqueConstraint(fields=('student', 'exercise'), name='student_exercise'),
        ),
    ]
