# Generated by Django 3.1.8 on 2022-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0102_measurement_measurementresult_measurementsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementresult',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='date',
            field=models.DateField(),
        ),
    ]
