# Generated by Django 3.1.8 on 2022-05-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0103_auto_20220503_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesstestgrading',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='fitnesstestresult',
            name='semester',
        ),
        migrations.AddField(
            model_name='fitnesstestsession',
            name='semester',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='sport.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnesstestresult',
            name='session',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sport.fitnesstestsession'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='fitnesstestresult',
            constraint=models.UniqueConstraint(fields=('student', 'exercise'), name='student_exercise'),
        ),
    ]
