# Generated by Django 3.1.8 on 2022-05-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0103_remove_fitnesstestgrading_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstestsession',
            name='semester',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='sport.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnesstestresult',
            name='session',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sport.fitnesstestsession'),
            preserve_default=False,
        ),
    ]
