# Generated by Django 3.1.8 on 2022-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0104_auto_20220502_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstestexercise',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
