# Generated by Django 3.1.8 on 2022-05-04 09:42

from django.db import migrations, models
import sport.models.measurement_session


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0105_measurement_measurementresult_measurementsession'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='measurementresult',
            constraint=models.UniqueConstraint(fields=('session', 'measurement'), name='session_measurement'),
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='date',
            field=models.DateField(default=sport.models.measurement_session.today),
        ),
    ]
