# Generated by Django 3.1.8 on 2022-05-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0106_auto_20220504_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='sport.student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='sport.training')),
            ],
        ),
    ]
