# Generated by Django 3.1.8 on 2022-08-23 21:58

from django.db import migrations, models
import django.db.models.deletion
import sport.models.semester


def create_courses(apps, schema_editor):
    Course = apps.get_model("sport", "Course")
    Course.objects.bulk_create([
        Course(course=1),
        Course(course=2),
        Course(course=3),
        Course(course=4),
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0109_auto_20220522_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='academic_leave_students',
            field=models.ManyToManyField(blank=True, default=sport.models.semester.academic_leave_students, related_name='academic_leave_semesters', to='sport.Student'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.trainer')),
            ],
        ),
        migrations.RunPython(create_courses, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='semester',
            name='participating_courses',
            field=models.ManyToManyField(blank=True, to='sport.Course'),
        ),
    ]
