# Generated by Django 3.1.8 on 2022-06-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0109_auto_20220522_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='allowed_qr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_QR',
        ),
    ]
