# Generated by Django 3.1.8 on 2022-08-25 11:30

from django.db import migrations, models
import sport.models.semester


def for_all_empty_semesters_set_all_courses(apps, schema_editor):
    Semester = apps.get_model("sport", "Semester")
    Course = apps.get_model("sport", "Course")
    for semester in Semester.objects.all():
        if not semester.participating_courses.exists():
            semester.participating_courses.set(Course.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0110_auto_20220824_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='participating_courses',
            field=models.ManyToManyField(default=sport.models.semester.all_courses, to='sport.Course'),
        ),
        migrations.RunPython(for_all_empty_semesters_set_all_courses, reverse_code=migrations.RunPython.noop),
    ]
