# Generated by Django 3.1.8 on 2022-08-25 13:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0111_auto_20220825_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
