# Generated by Django 3.1.8 on 2022-08-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0112_sport_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
        migrations.RemoveField(
            model_name='group',
            name='link_name',
        ),
    ]
