# Generated by Django 3.1.8 on 2022-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0113_auto_20220825_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sport__isnull', False),
                                                                      models.Q(('name__isnull', False),
                                                                               models.Q(_negated=True, name__exact='')),
                                                                      _connector='OR')), name='sport_or_name'),
        ),
    ]
