# Generated by Django 3.1.8 on 2022-09-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0116_student_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fitnesstestresult',
            name='student_exercise',
        ),
    ]
