# Generated by Django 3.1.8 on 2022-11-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0117_auto_20220924_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sport.training'),
        ),
    ]
