# Generated by Django 3.1.8 on 2023-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0118_auto_20221121_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='accredited',
            field=models.BooleanField(default=False),
        ),
    ]
