# Generated by Django 3.1.8 on 2023-01-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0121_group_allowed_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcheckin',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='sport.training'),
        ),
    ]
