# Generated by Django 3.1.8 on 2023-02-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0122_auto_20230127_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcheckin',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='sport.training'),
        ),
    ]
