# Generated by Django 4.2 on 2024-11-28 09:58

from django.db import migrations, models
import django.db.models.deletion
import sport.models.medical_group_reference


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0123_auto_20230205_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalgroupreference',
            name='image',
        ),
        migrations.CreateModel(
            name='MedicalGroupReferenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sport.models.medical_group_reference.get_reference_path)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sport.medicalgroupreference', verbose_name='medical reference')),
            ],
            options={
                'verbose_name': 'medical group reference image',
                'verbose_name_plural': 'medical group reference images',
                'db_table': 'medical_group_reference_image',
            },
        ),
    ]
