name: sport

services:
  nginx:
    # See more: https://registry.hub.docker.com/_/nginx
    image: "nginx:1.27"
    restart: unless-stopped
    ports: [ "80:80" ]
    depends_on:
      - adminpanel
    volumes:
      - "./nginx-conf/dev.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx-logs:/var/log/nginx"
      - django-static:/static
      - uploaded_media:/media:ro

  adminpanel:
    build:
      context: ../adminpage
      args:
        - PYTHON_VERSION=3.7
    #   Wait for postgres to startup before running server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    restart: unless-stopped
    volumes:
      - "../adminpage:/src"
      - "django-auth-preserve:/usr/local/lib/python${PYTHON_VERSION}/site-packages/django/contrib/auth/migrations/"
      - "django-static:/static"
      - "uploaded_media:/uploaded_media"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DEBUG: 'true'

  db:
    # See more: https://registry.hub.docker.com/_/postgres
    image: "postgres:11-alpine"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - .env

  prometheus:
    # See more: https://registry.hub.docker.com/r/prom/prometheus
    image: "prom/prometheus:v2.55.1"
    restart: unless-stopped
    volumes:
      - "./prometheus:/etc/prometheus"
    ports:
      - "9090:9090"

  prometheus-postgres:
    # See more: https://github.com/prometheus-community/postgres_exporter
    image: "quay.io/prometheuscommunity/postgres-exporter:v0.16.0"
    restart: unless-stopped
    environment:
      DATA_SOURCE_URI: "${POSTGRES_SERVER}:5432/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: "${POSTGRES_USER}"
      DATA_SOURCE_PASS: "${POSTGRES_PASSWORD}"
    ports:
      - "9187:9187"
    depends_on:
      - db

  grafana:
    # See more: https://registry.hub.docker.com/r/grafana/grafana
    image: "grafana/grafana:11.3.1"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-EMAIL"
      GF_AUTH_PROXY_HEADER_PROPERTY: "email"
      GF_AUTH_PROXY_HEADERS: "Name:X-WEBAUTH-NAME"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_SYNC_TTL: "0"
    env_file:
      - .env
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./grafana-provisioning:/etc/grafana/provisioning/"

  adminer:
    # See more: https://registry.hub.docker.com/_/adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  db-data:
  django-static:
  grafana-data:
  # required to preserve change to django.contrib.auth.models.Group class.
  # (verbose_name added)
  # since Innopolis adfs provides groupsid as universal identifier
  # (group - can be either in Russian or English)
  django-auth-preserve:
  uploaded_media:
