name: sport

services:
  adminpanel:
    build:
      context: ../adminpage
      args:
        PYTHON_VERSION: 3.7
    #   Wait for postgres to startup before running server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.test

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    env_file:
      - .env.test
