# Generated by Django 3.1.8 on 2022-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_suggestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
