# Generated by Django 3.1.8 on 2022-09-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0111_auto_20220825_1430'),
        ('training_suggestor', '0003_poll_pollanswer_pollquestion_pollresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_suggestor_user', to='sport.student'),
        ),
        migrations.AlterUniqueTogether(
            name='pollanswer',
            unique_together={('result', 'question')},
        ),
    ]
