# Generated by Django 3.1.8 on 2022-10-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_suggestor', '0004_auto_20220915_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training_suggestor.pollresult'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='answers',
            field=models.JSONField(blank=True, default=[], help_text='json array of answers', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pollquestion',
            unique_together={('poll', 'state')},
        ),
    ]
