version: '3.5'
services:
  nginx:
    restart: always
    build:
      context: ../nginx
    ports:
      - "80:80"
    depends_on:
      - adminpanel
    volumes:
      - ../nginx/logs:/var/log/nginx
      - ../nginx/access.d:/etc/nginx/access.d
      - django-static:/static
      - /sport/media:/media:ro

  adminpanel:
    build:
      context: ../adminpage
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION
    #   Wait for postgres to startup before running server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn adminpage.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --lifespan off --proxy-headers'
    restart: always
    volumes:
      - django-auth-preserve:/usr/local/lib/python${PYTHON_VERSION}/site-packages/django/contrib/auth/migrations/
      - django-static:/static
      - /sport/media:/uploaded_media
    depends_on:
      - db
    env_file:
      - .env

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/dashboard"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_LDAP_SYNC_TTL: "60"
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/provisioning/:/etc/grafana/provisioning/

  db:
    image: db
    build:
      context: ..
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  db-data:
  django-static:
  grafana-data:
  # required to preserve change to django.contrib.auth.models.Group class.
  # (verbose_name added)
  # since Innopolis adfs provides groupsid as universal identifier
  # (group - can be either in Russian or English)
  django-auth-preserve:
