from .crud_attendance import *
from .crud_enrolled import *
from .crud_groups import *
from .crud_schedule import *
from .crud_semester import *
from .crud_training import *
from .crud_users import *
from .crud_faq import *
from .crud_fitness_test import *
from .crud_measurement import *
