name: New.sport deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to staging server
    runs-on: self-hosted
    environment:
      name: new-sport-env
      url: https://new.sport.innopolis.university
    steps:
      - name: Change permissions
        run: "[ -d $FILE ] && echo github | sudo -S chown -R $USER:$USER $FILE"
        env:
          FILE: ${{ github.workspace }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get env file
        run: cp -f /home/github_actions/.env /home/github_actions/actions-runner/_work/SWP_sport_back/SWP_sport_back/compose
      - name: Deploy via Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start.yml
          directory: ./ansible
